FROM eclipse-temurin:21-jre-alpine

RUN apk add --no-cache bash fontconfig curl java-cacerts \
    && mkdir -p /app/certs \
    && /opt/java/openjdk/bin/keytool -noprompt -import -trustcacerts -alias azure-cert -file /app/certs/DigiCertGlobalRootG2.crt.pem -keystore /etc/ssl/certs/java/cacerts -keypass changeit -storepass changeit \
    && mkdir -p /plugins && chmod a+rwx /plugins

COPY bin/docker/DigiCertGlobalRootG2.crt.pem /app/certs/DigiCertGlobalRootG2.crt.pem
COPY dist/app.jar /app/metabase.jar
COPY dist/start_mb_docker.sh /app/run_metabase.sh
RUN chmod +x /app/run_metabase.sh

EXPOSE 3000

ENTRYPOINT ["/app/run_metabase.sh"]
